<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

// Get POST data
$data = json_decode(file_get_contents('php://input'), true);

if (!$data) {
    echo json_encode(['success' => false, 'error' => 'No data received']);
    exit;
}

$userEmail = $data['email'] ?? '';
$playerName = $data['playerName'] ?? 'Unknown';
$gameName = $data['gameName'] ?? 'The Masked Employee';
$language = $data['language'] ?? 'nl';

// Admin email (change this to your email)
$adminEmail = 'klaas@pinkmilk.eu';

// Log all data for debugging
error_log("=== EMAIL REQUEST START ===");
error_log("User Email: $userEmail");
error_log("Player Name: $playerName");
error_log("Game Name: $gameName");
error_log("Language: $language");
error_log("Admin Email: $adminEmail");

// Validate email
if (!filter_var($userEmail, FILTER_VALIDATE_EMAIL)) {
    echo json_encode(['success' => false, 'error' => 'Invalid email address']);
    exit;
}

// Email content based on language
if ($language === 'nl') {
    $subject = '🎭 Bedankt voor je deelname aan ' . $gameName;
    $userMessage = "
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #8A2BE2, #9932CC); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
            .footer { text-align: center; margin-top: 20px; color: #666; font-size: 0.9em; }
            h1 { margin: 0; font-size: 1.8em; }
            .emoji { font-size: 2em; }
        </style>
    </head>
    <body>
        <div class='container'>
            <div class='header'>
                <div class='emoji'>🎭</div>
                <h1>Bedankt voor je deelname!</h1>
            </div>
            <div class='content'>
                <h2>Hallo " . htmlspecialchars($playerName) . "!</h2>
                
                <p>Bedankt voor het invullen van de vragenlijst voor <strong>" . htmlspecialchars($gameName) . "</strong>!</p>
                
                <p>🎨 <strong>Wat gebeurt er nu?</strong></p>
                <ul>
                    <li>Je unieke karakter wordt gegenereerd door AI</li>
                    <li>We maken een mysterieuze video van je karakter</li>
                    <li>Binnenkort ontvang je meer informatie over de show</li>
                </ul>
                
                <p style='background: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0;'>
                    <strong>⚠️ Belangrijk:</strong> Vergeet niet dat absolute geheimhouding verplicht is! 
                    Vertel niemand over je deelname aan de show.
                </p>
                
                <p>Tot snel bij de show! 🎭</p>
                
                <p>Met vriendelijke groet,<br>
                Het Masked Employee Team</p>
            </div>
            <div class='footer'>
                <p>Dit is een automatisch gegenereerde email</p>
            </div>
        </div>
    </body>
    </html>
    ";
    
    $adminSubject = '🎭 Nieuwe deelname: ' . $playerName;
} else {
    $subject = '🎭 Thank you for participating in ' . $gameName;
    $userMessage = "
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #8A2BE2, #9932CC); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
            .footer { text-align: center; margin-top: 20px; color: #666; font-size: 0.9em; }
            h1 { margin: 0; font-size: 1.8em; }
            .emoji { font-size: 2em; }
        </style>
    </head>
    <body>
        <div class='container'>
            <div class='header'>
                <div class='emoji'>🎭</div>
                <h1>Thank you for participating!</h1>
            </div>
            <div class='content'>
                <h2>Hello " . htmlspecialchars($playerName) . "!</h2>
                
                <p>Thank you for completing the questionnaire for <strong>" . htmlspecialchars($gameName) . "</strong>!</p>
                
                <p>🎨 <strong>What happens next?</strong></p>
                <ul>
                    <li>Your unique character is being generated by AI</li>
                    <li>We'll create a mysterious video of your character</li>
                    <li>You'll receive more information about the show soon</li>
                </ul>
                
                <p style='background: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0;'>
                    <strong>⚠️ Important:</strong> Remember that absolute confidentiality is required! 
                    Don't tell anyone about your participation in the show.
                </p>
                
                <p>See you at the show! 🎭</p>
                
                <p>Best regards,<br>
                The Masked Employee Team</p>
            </div>
            <div class='footer'>
                <p>This is an automatically generated email</p>
            </div>
        </div>
    </body>
    </html>
    ";
    
    $adminSubject = '🎭 New participant: ' . $playerName;
}

// Admin notification email
$adminMessage = "
<html>
<body style='font-family: Arial, sans-serif;'>
    <h2>🎭 Nieuwe deelname aan " . htmlspecialchars($gameName) . "</h2>
    
    <p><strong>Deelnemer:</strong> " . htmlspecialchars($playerName) . "</p>
    <p><strong>Email:</strong> " . htmlspecialchars($userEmail) . "</p>
    <p><strong>Taal:</strong> " . strtoupper($language) . "</p>
    <p><strong>Tijdstip:</strong> " . date('d-m-Y H:i:s') . "</p>
    
    <p>Bekijk de volledige gegevens in PocketBase.</p>
</body>
</html>
";

// Email headers
$headers = "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
$headers .= "From: The Masked Employee <noreply@pinkmilk.eu>" . "\r\n";

// Send email to user
$userEmailSent = mail($userEmail, $subject, $userMessage, $headers);

// Log user email attempt
error_log("User email to $userEmail: " . ($userEmailSent ? 'SUCCESS' : 'FAILED'));

// Try sending a simple text-only admin email first
$simpleAdminMessage = "New Masked Employee Participant!\n\n";
$simpleAdminMessage .= "Deelnemer: $playerName\n";
$simpleAdminMessage .= "Email: $userEmail\n";
$simpleAdminMessage .= "Taal: " . strtoupper($language) . "\n";
$simpleAdminMessage .= "Tijdstip: " . date('d-m-Y H:i:s') . "\n\n";
$simpleAdminMessage .= "Bekijk de volledige gegevens in PocketBase.";

$simpleHeaders = "From: Masked Employee <noreply@pinkmilk.eu>" . "\r\n";
$simpleHeaders .= "Reply-To: $userEmail" . "\r\n";

error_log("Attempting to send admin email to: $adminEmail");
error_log("Subject: $adminSubject");
error_log("From: noreply@pinkmilk.eu");

$adminEmailSent = mail($adminEmail, $adminSubject, $simpleAdminMessage, $simpleHeaders);

// Log admin email attempt with more details
if ($adminEmailSent) {
    error_log("✅ Admin email SENT successfully to $adminEmail");
} else {
    error_log("❌ Admin email FAILED to $adminEmail");
    $lastError = error_get_last();
    if ($lastError) {
        error_log("Last PHP error: " . print_r($lastError, true));
    }
}

error_log("=== EMAIL REQUEST END ===");

// Response - consider success if at least user email sent
if ($userEmailSent) {
    echo json_encode([
        'success' => true,
        'message' => 'Email sent successfully',
        'userEmail' => $userEmail,
        'userEmailSent' => $userEmailSent,
        'adminEmailSent' => $adminEmailSent,
        'note' => $adminEmailSent ? 'Both emails sent' : 'User email sent, admin email may be delayed'
    ]);
} else {
    echo json_encode([
        'success' => false,
        'error' => 'Failed to send user email',
        'userEmailSent' => $userEmailSent,
        'adminEmailSent' => $adminEmailSent
    ]);
}
?>
